name: Release

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile

jobs:
  release:
    permissions:
      contents: read
      packages: write
    uses: $/.github/workflows/common.yaml
